import Head from 'next/head';
import React from 'react';
import DefaultFooter from '../components/DefaultFooter';
import DefaultHeader from '../components/DefaultHeader';

const DefaultLayout = ({ children }) =>
  <>
    <Head>
      <title>Next Custom</title>
      <meta name="description" content="Generated by App custom" />
      <link rel="icon" href="https://kenh14cdn.com/thumb_w/660/2020/5/28/0-1590653959375414280410.jpg" />
    </Head>
    <DefaultHeader />
    <main className='container mx-auto'>{children}</main>
    <DefaultFooter />
  </>



export default DefaultLayout;