import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>App custom</title>
        <meta name="description" content="Generated by App custom" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Image
        src="/images/profile.jpg" // Route of the image file
        height={144} // Desired size with correct aspect ratio
        width={144} // Desired size with correct aspect ratio
        alt="Your Name1"
      />
    </>
  );
}
